PLAY_TYPE_CATEGORIES = {
    'ASSIST': ['assist'],
    'BAD_PASS': ['turnover'],
    'BASELINE_J': ['mid', 'shot'],
    'BLOWOUT': ['info'],
    'BUZZERBEATER': ['info'],
    'CORNER_THREE': ['three', 'shot'],
    'DOUBLE_DOUBLE': ['info'],
    'DRIVING_LAYUP': ['inside', 'shot'],
    'DUNK': ['dunk', 'shot', 'inside'],
    'DUNK_MISSED': ['dunk', 'shot', 'inside'],
    'ELBOW': ['mid', 'shot'],
    'FALL_AWAY': ['mid', 'shot'],
    'FREE_THROW_MADE': ['ft'],
    'FREE_THROW_MISSED': ['ft'],
    'HALF_COURT_SHOT': ['three', 'shot'],
    'HALF_OVER': ['info'],
    'HOOK': ['inside', 'shot'],
    'INJURY': ['info'],
    'JUMP_BALL': ['info'],
    'LAYUP': ['inside', 'shot'],
    'NOSHOOT_FOUL': ['foul'],
    'OFF_FOUL': ['foul'],
    'PERIOD_OVER': ['info'],
    'PUTBACK': ['inside', 'shot'],
    'REBOUND': ['rebound'],
    'REBOUND_OOB': ['info'],
    'SHOOTING_FOUL': ['foul'],
    'SHOT_CLOCK_ZERO': ['info'],
    'SHOTSTREAKMAKE': ['info'],
    'SHOTSTREAKMISS': ['info'],
    'SPINNY': ['mid', 'shot'],
    'STEAL': ['steal'],
    'STEAL_ON_PASS': ['steal'],
    'STRAIGHT_ON_THREE': ['three', 'shot'],
    'STRONG': ['inside', 'shot'],
    'SUBSTITUTION': ['info'],
    'SUBSTITUTION_SWAP': ['info'],
    'TECHNICAL': ['foul'],
    'THREE_SECOND': ['turnover'],
    'TIME_OUT': ['info'],
    'TIPBACK': ['inside', 'shot'],
    'TIPBACKDUNK': ['dunk', 'shot', 'inside'],
    'TOPKEY': ['mid', 'shot'],
    'TRIPLE_DOUBLE': ['info'],
    'QUADRUPLE_DOUBLE': ['info'],
    'TRAVEL': ['turnover'],
    'VERY_LONG': ['three', 'shot'],
    'WING': ['mid', 'shot'],
    'WING_THREE': ['three', 'shot']
}

